version: "3.4"

services:
  xl-deploy-lb:
    image: xebialabsunsupported/haproxy
    container_name: xl-deploy-lb
    depends_on:
      - xl-deploy-master
    ports:
      - "{{PUBLIC_PORT}}:5000"
      - "{{HA_PORT}}:1936"
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    environment:
      BACKENDS: "xl-deploy-master:4516"
      HTTPCHK: "GET /deployit/ha/health"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      COOKIES_PARAMS: "SESSION_XLD prefix"
      LOG_LEVEL: "info"
      TIMEOUT_CONNECT: 60000

  xl-deploy-master:
    image: {{DEPLOY_MASTER_IMAGE}}
    depends_on:
      - rabbitmq
      - postgresql
    restart: unless-stopped
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    environment:
      - ACCEPT_EULA=Y
      - ADMIN_PASSWORD=admin
      - FORCE_UPGRADE=true
      - XL_CLUSTER_MODE=default
      - XL_DB_PASSWORD=admin
      - XL_DB_USERNAME=postgres
      - XL_DB_URL=jdbc:postgresql://postgresql:5432/xld-db
      - XLD_IN_PROCESS=false
      - XLD_TASK_QUEUE_DRIVER_CLASS_NAME=com.rabbitmq.jms.admin.RMQConnectionFactory
      - XLD_TASK_QUEUE_PASSWORD=admin
      - XLD_TASK_QUEUE_USERNAME=rabbitmq
      - XLD_TASK_QUEUE_URL=amqp://rabbitmq:5672
      - USE_IP_AS_HOSTNAME=true
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-server/centralConfiguration:/opt/xebialabs/xl-deploy-server/centralConfiguration:z
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-server/conf:/opt/xebialabs/xl-deploy-server/conf:z
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-server/plugins:/opt/xebialabs/xl-deploy-server/plugins:z

  rabbitmq:
    image: {{RABBIT_MQ_IMAGE}}
    container_name: rabbitmq
    hostname: "rabbit"
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_LOOPBACK_USERS: none
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/rabbitmq:/etc/rabbitmq

  postgresql:
    image: {{POSTGRES_IMAGE}}
    container_name: postgresql
    ports:
      - "{{DB_PORT}}:5432"
    environment:
      - POSTGRES_DB=xld-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    command: {{POSGRES_COMMAND}}
    networks:
      - {{DEPLOY_NETWORK_NAME}}

networks:
  {{DEPLOY_NETWORK_NAME}}:
    external: true
