version: "3.4"

services:
  xl-deploy-lb:
    image: xebialabsunsupported/haproxy
    container_name: xl-deploy-lb
    depends_on:
      - xl-deploy-master
    ports:
      - "{{PUBLIC_PORT}}:5000"
      - "{{HA_PORT}}:1936"
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    environment:
      BACKENDS: "xl-deploy-master:4516"
      HTTPCHK: "GET /deployit/ha/health"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      COOKIES_PARAMS: "SESSION_XLD prefix"
      LOG_LEVEL: "info"
      TIMEOUT_CONNECT: 60000

  xl-deploy-master:
    image: {{DEPLOY_MASTER_IMAGE}}
    depends_on:
      - rabbitmq
      - postgresql
    restart: unless-stopped
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    environment:
      - ACCEPT_EULA=Y
      - ADMIN_PASSWORD=admin
      - FORCE_UPGRADE=true
      - XL_CLUSTER_MODE=default
      - XL_DB_PASSWORD=admin
      - XL_DB_USERNAME=postgres
      - XL_DB_URL=jdbc:postgresql://postgresql:5432/xld-db
      - XL_REPORT_DB_URL=jdbc:postgresql://postgresql:5432/xld-db
      - XL_REPORT_DB_USERNAME=postgres
      - XL_REPORT_DB_PASSWORD=admin
      - XLD_IN_PROCESS=false
      - XLD_TASK_QUEUE_DRIVER_CLASS_NAME=com.rabbitmq.jms.admin.RMQConnectionFactory
      - XLD_TASK_QUEUE_PASSWORD=admin
      - XLD_TASK_QUEUE_USERNAME=rabbitmq
      - XLD_TASK_QUEUE_URL=amqp://rabbitmq:5672
      - USE_IP_AS_HOSTNAME=true
      - REPOSITORY_KEYSTORE_PASSPHRASE=deployit
      - CENTRAL_CONFIG_ENCRYPT_KEY=changeme
      - XL_LICENSE=LS0tIExpY2Vuc2UgLS0tCkxpY2Vuc2UgdmVyc2lvbjogNApQcm9kdWN0OiBYTCBEZXBsb3kKTGljZW5zZWQgdG86IFhlYmlhTGFicwpDb250YWN0OiBYZWJpYUxhYnMgSW50ZXJuYWwgVXNlIE9ubHkgPGluZm9AeGViaWFsYWJzLmNvbT4KRXhwaXJlcyBhZnRlcjogMjAzNy0wMS0wMQpMaWNlbnNlZCBudW1iZXIgb2YgQ0lzOiB4bC5TYXRlbGxpdGU9MTAwMApMaWNlbnNlZCBwbHVnaW46IGJpenRhbGstcGx1Z2luCkxpY2Vuc2VkIHBsdWdpbjogZ2xhc3NmaXNoLXBsdWdpbgpMaWNlbnNlZCBwbHVnaW46IGlpcy1wbHVnaW4KTGljZW5zZWQgcGx1Z2luOiBqYm9zc2FzLXBsdWdpbgpMaWNlbnNlZCBwbHVnaW46IGpib3NzZG0tcGx1Z2luCkxpY2Vuc2VkIHBsdWdpbjogb3NiLXBsdWdpbgpMaWNlbnNlZCBwbHVnaW46IHRvbWNhdC1wbHVnaW4KTGljZW5zZWQgcGx1Z2luOiB3YXMtcGx1Z2luCkxpY2Vuc2VkIHBsdWdpbjogd2luZG93cy1wbHVnaW4KTGljZW5zZWQgcGx1Z2luOiB3bHMtcGx1Z2luCkxpY2Vuc2VkIHBsdWdpbjogd21xLXBsdWdpbgpMaWNlbnNlZCBwbHVnaW46IHdwcy1wbHVnaW4KU3VwcG9ydCBwb2xpY3k6IDh4NQpFZGl0aW9uOiBFc3NlbnRpYWxzCi0tLSBTaWduYXR1cmUgKFNIQTF3aXRoRFNBKSAtLS0KMzAyYzAyMTQyMDhhYjAwZTlmODAyMjI0ZWE1YWIzMzY5OGYxODFkNmNhNDAxYWY2MDIxNDI0NmI1MGU5YjZhMWJmMGIyNWFiNGY0NGIyNTkKNDkyMmI5MDFjMGQyCi0tLSBFbmQgb2YgU2lnbmF0dXJlIC0tLQ==
      - REPOSITORY_KEYSTORE=zs7OzgAAAAIAAAABAAAAAwAWZGVwbG95aXQtcGFzc3N3b3JkLWtleQAAAX0FGMZRrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAARMA8ECHAyz3pefALRAgMDDUB1cQB+AAUAAACQb6Y2JUQqkd5PtdwIAKEWNiVMcTnIS85U7FsvOb+b+xfOCV8+disezZCQ2f4F6YVGRO++u+NXd0YNDn/eXwge4w7i4ewNBydpMSTpVJieJA3nhh7mvUktatsAV+H7EcGYeMPx/cAlkqyFUHuiGz9p1ft3pxmxey2Uyt/FiBgAiV2hZAj14vGdSoRsMH8qN5ECdAAWUEJFV2l0aE1ENUFuZFRyaXBsZURFU3QAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVO9rqwVmysM6czWLFdUj1+Xh1hxHQ==
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-server/centralConfiguration:/opt/xebialabs/xl-deploy-server/centralConfiguration:z
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-server/plugins:/opt/xebialabs/xl-deploy-server/plugins:z

  rabbitmq:
    image: {{RABBIT_MQ_IMAGE}}
    container_name: rabbitmq
    hostname: "rabbit"
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_LOOPBACK_USERS: none
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/rabbitmq:/etc/rabbitmq

  postgresql:
    image: {{POSTGRES_IMAGE}}
    container_name: postgresql
    ports:
      - "{{DB_PORT}}:5432"
    environment:
      - POSTGRES_DB=xld-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    command: {{POSGRES_COMMAND}}
    networks:
      - {{DEPLOY_NETWORK_NAME}}

networks:
  {{DEPLOY_NETWORK_NAME}}:
    external: true
