version: "3.4"

services:
  xl-deploy-worker:
    image: {{DEPLOY_WORKER_IMAGE}}
    restart: unless-stopped
    networks:
      - {{DEPLOY_NETWORK_NAME}}
    environment:
      - ACCEPT_EULA=Y
      - ADMIN_PASSWORD=admin
      - XL_CLUSTER_MODE=default
      - XL_DB_PASSWORD=admin
      - XL_DB_USERNAME=postgres
      - XL_DB_URL=jdbc:postgresql://{{JDBC_URL}}
      - XLD_IN_PROCESS=false
      - XLD_TASK_QUEUE_DRIVER_CLASS_NAME=com.rabbitmq.jms.admin.RMQConnectionFactory
      - XLD_TASK_QUEUE_PASSWORD=admin
      - XLD_TASK_QUEUE_USERNAME=rabbitmq
      - XLD_TASK_QUEUE_URL=amqp://rabbitmq:5672
      - USE_IP_AS_HOSTNAME=true
    command:
      - changeMe
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-worker/conf:/opt/xebialabs/deploy-task-engine/conf:z
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/xl-deploy-worker/plugins:/opt/xebialabs/deploy-task-engine/plugins:z

networks:
  {{DEPLOY_NETWORK_NAME}}:
    external: true
