version: "3.4"

services:
  mysql:
    image: mysql:5.7.15
    command: --max_allowed_packet=100M
    ports:
      - "{{PUBLIC_PORT}}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=xld
      - MYSQL_USER=xldrepo
      - MYSQL_PASSWORD=xldrepo
