version: "3.3"

services:
  mysql:
    container_name: is-mysql
    image: mysql:5.7.15
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=xld
      - MYSQL_USER=xldrepo
      - MYSQL_PASSWORD=xldrepo
