version: "3.4"

services:
  postgres:
    image: postgres:10.5
    working_dir: /
    ports:
      - "{{DB_PORT}}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=xldrepo
    command: postgres
