version: "3.4"

services:
  postgres:
    image: postgres:12-bullseye
    ports:
       - "33962:5432"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=demo
    command: postgres
