version: "3.3"

services:
  mysql:
    container_name: is-mysql-8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=100M
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=xld
      - MYSQL_USER=xldrepo
      - MYSQL_PASSWORD=xldrepo
