spring:
  profiles:
    active: native
  cloud:
    config:
      fail-fast: true
      server:
        prefix: centralConfiguration
    httpclientfactories:
      apache:
        enabled: true
      ok:
        enabled: false
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
