version: "3.4"

services:
  cc:
    image: {{CC_IMAGE_VERSION}}
    container_name: central-configuration
    networks:
      - "xld-network"
    ports:
      - "8888:8888"
    environment:
      - CENTRAL_CONFIG_ENCRYPT_KEY=changeme
networks:
  xld-network:
    external: true