swagger: "2.0"
host: "{{NAME}}.endpoints.{{PROJECT_ID}}.cloud.goog"
x-google-endpoints:
- name: "{{NAME}}.endpoints.{{PROJECT_ID}}.cloud.goog"
  target: "{{IP}}"
info:
  title: "{{NAME}} in {{PROJECT_ID}}"
  version: 1.0.0
paths: {}
