swagger: "2.0"
host: "{{PRODUCT_NAME}}-{{HOST}}-{{NAMESPACE}}.endpoints.{{PROJECT_ID}}.cloud.goog"
x-google-endpoints:
- name: "{{PRODUCT_NAME}}-{{HOST}}-{{NAMESPACE}}.endpoints.{{PROJECT_ID}}.cloud.goog"
  target: "{{IP}}"
info:
  title: "{{HOST}}-{{NAMESPACE}} for {{PRODUCT_NAME}} in {{PROJECT_ID}}"
  version: 1.0.0
paths: {}