version: "3.4"

services:
  deploy-{{DEPLOY_VERSION}}:
    image: {{DEPLOY_IMAGE_VERSION}}
    container_name: deploy-{{DEPLOY_VERSION}}
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
      - GENERATE_XL_CONFIG=false
      - PLUGINS_TO_EXCLUDE={{DEPLOY_PLUGINS_TO_EXCLUDE}}
      - FORCE_UPGRADE={{DEPLOY_FORCE_UPGRADE}}
      - PLUGIN_SOURCE=filesystem
    ports:
      - {{DEPLOY_SERVER_HTTP_PORT}}:4516
    volumes:
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/centralConfiguration:/opt/xebialabs/xl-deploy-server/centralConfiguration
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/conf:/opt/xebialabs/xl-deploy-server/conf
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/hotfix/lib:/opt/xebialabs/xl-deploy-server/hotfix/lib
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/hotfix/plugins:/opt/xebialabs/xl-deploy-server/hotfix/plugins
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/export:/opt/xebialabs/xl-deploy-server/export
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/ext:/opt/xebialabs/xl-deploy-server/ext
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/importablePackages:/opt/xebialabs/xl-deploy-server/importablePackages
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/work:/opt/xebialabs/xl-deploy-server/work
      - {{INTEGRATION_SERVER_ROOT_VOLUME}}/repository:/opt/xebialabs/xl-deploy-server/repository
      - ./plugins:/opt/xebialabs/xl-deploy-server/plugins
