CrName: {{CR_NAME}}
CrdName: {{CRD_NAME}}
DeployImageVersionForUpgrader: {{DEPLOY_VERSION_FOR_UPGRADER}}
K8sApiServerURL: {{K8S_API_SERVER_URL}}
K8sClientCert: {{K8S_CLIENT_CERT}}
K8sClientKey: {{K8S_CLIENT_KEY}}
K8sSetup: {{K8S_SETUP}}
Namespace: {{K8S_NAMESPACE}}
OperatorImage: {{OPERATOR_IMAGE}}
OperatorImageDeployGeneric: {{OPERATOR_IMAGE}}
RepositoryName: {{REPOSITORY_NAME}}
ImageNameDeploy: xl-deploy
ImageNameDeployTaskEngine: deploy-task-engine
ImageTag: {{IMAGE_TAG}}
OsType: darwin
ServerType: daiDeploy
UpgradeType: operatorToOperator
UseCustomNamespace: {{USE_CUSTOM_NAMESPACE}}
IsCrdReused: {{IS_CRD_REUSED}}
UseKubeconfig: true
InstallXLD: false
UseEmbeddedKeycloak: {{USE_KEYCLOAK}}
UseExistingOidcConf: false
KeycloakUrl: {{KEYCLOAK_URL}}
EnableOidc: false
UseOperatorZipDeploy: {{USE_OPERATOR_ZIP}}
OperatorZipDeploy: {{OPERATOR_ZIP_DEPLOY}}
PreserveCrValuesDeploy: |-
  .spec.nginx-ingress-controller.service.annotations
  .spec.XldMasterCount
  .spec.XldWorkerCount
  .spec.Persistence.XldMasterPvcSize
  .spec.Persistence.XldWorkerPvcSize
  .spec.ingress.hosts
  .spec.KeystorePassphrase
  .spec.Persistence.StorageClass
  .spec.RepositoryKeystore
  .spec.postgresql.persistence.size
  .spec.postgresql.persistence.storageClass
  .spec.postgresql.postgresqlMaxConnections
  .spec.keycloak.postgresql.postgresqlMaxConnections
  .spec.keycloak.install
  .spec.oidc.enabled
  .spec.rabbitmq.persistence.storageClass
  .spec.rabbitmq.persistence.size
  .spec.rabbitmq.replicaCount
  .spec.rabbitmq.persistence.replicaCount
  .spec.route.hosts
  .spec.xldLicense
