CrName: {{CR_NAME}}
CrdName: {{CRD_NAME}}
K8sApiServerURL: {{K8S_API_SERVER_URL}}
K8sClientCert: {{K8S_CLIENT_CERT}}
EksClusterName: {{CLUSTER_NAME}}
AWSAccessKey: {{AWS_ACCESS_KEY}}
AWSAccessSecret: {{AWS_ACCESS_SECRET}}
K8sSetup: {{K8S_SETUP}}
Namespace: default
OperatorImage: {{OPERATOR_IMAGE}}
OperatorImageDeployGeneric: {{OPERATOR_IMAGE}}
RepositoryName: {{REPOSITORY_NAME}}
ImageNameDeploy: xl-deploy
ImageNameDeployTaskEngine: deploy-task-engine
ImageTag: {{IMAGE_TAG}}
OsType: darwin
ServerType: daiDeploy
UpgradeType: operatorToOperator
UseCustomNamespace: true
UseKubeconfig: true
InstallXLD: false
IsEKS: true
UseAWSconfig: true
UseOperatorZipDeploy: true
OperatorZipDeploy: {{OPERATOR_ZIP_DEPLOY}}
PreserveCrValuesDeploy: |-
  .spec.XldMasterCount
  .spec.XldWorkerCount
  .spec.Persistence.XldMasterPvcSize
  .spec.Persistence.XldWorkerPvcSize
  .spec.ingress.hosts
  .spec.KeystorePassphrase
  .spec.Persistence.StorageClass
  .spec.RepositoryKeystore
  .spec.postgresql.persistence.size
  .spec.postgresql.persistence.storageClass
  .spec.postgresql.postgresqlMaxConnections
  .spec.keycloak.postgresql.postgresqlMaxConnections
  .spec.keycloak.install
  .spec.oidc.enabled
  .spec.rabbitmq.persistence.replicaCount
  .spec.rabbitmq.persistence.size
  .spec.rabbitmq.persistence.storageClass
  .spec.rabbitmq.replicaCount
  .spec.route.hosts
  .spec.xldLicense
