CREATE DATABASE xldrepo COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
USE xldrepo;
GO
CREATE LOGIN xldrepo WITH PASSWORD = 'xldrepo', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF, DEFAULT_DATABASE = xldrepo;
GO
CREATE USER [xldrepo] FOR LOGIN [xldrepo];
EXEC sp_addrolemember N'db_owner', N'xldrepo';
GO
ALTER DATABASE xldrepo SET ALLOW_SNAPSHOT_ISOLATION ON;
GO
ALTER DATABASE xldrepo SET READ_COMMITTED_SNAPSHOT ON;
GO
